### ISSUE TITLE
I hava a question

### ISSUE THREAD

**Issue by jhmarryme** [victorths/getx_nested_router_outlets#1]
Hello, I download and run this demo

When I press the button[To route C] , the jump does occur, but the entire page is replaced (the top appbar disappears), instead of being displayed in GetRouterOutlet,

Shouldn't the c page be displayed only in this area?

GetRouterOutlet(
    initialRoute: Routes.c,
    anchorRoute: Routes.homeA,
    delegate: Get.rootDelegate,
  ),

![image](https://github.com/victorths/getx_nested_router_outlets/assets/40780905/d28e4dcd-1675-4574-808f-47ee03264237)

![image](https://github.com/victorths/getx_nested_router_outlets/assets/40780905/c02f76b2-ff07-439c-91fb-11accc42a800)

If you are free, please take the time to answer my questions, or provide your contact information and I will contact you.

**Comment by victorths** [comment]
The project was to report a bug on the get package, it still open. I recommend you the flutter_modular package.

**Comment by jhmarryme** [comment]
Thanks, but I prefer to use getx. Finally, I used navigator to implement multiple nested routing, but the relative amount of code increased.
Thank you very much for your reply
